import { useEffect, useState } from 'react'
import { aiAPI, benefitsAPI, meAPI, subscribeToEvents, type Benefit, type PromoCode, type Redemption } from '../api/client'
import { useAuth } from '../context/AuthContext'

export default function EmployeeDashboard() {
  const { user, logout } = useAuth()
  const [benefits, setBenefits] = useState<Benefit[]>([]); const [promos, setPromos] = useState<PromoCode[]>([]); const [redemptions, setRedemptions] = useState<Redemption[]>([])
  const [query, setQuery] = useState(''); const [recommendations, setRecommendations] = useState<Benefit[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState('')
  const load = async () => { try { const [b, p, r] = await Promise.all([benefitsAPI.list({ page: 1, page_size: 50 }), meAPI.promoCodes({ page: 1, page_size: 20 }), meAPI.redemptions({ page: 1, page_size: 20 })]); setBenefits(b.data.items); setPromos(p.data.items); setRedemptions(r.data.items); setError('') } catch { setError('Не удалось загрузить каталог') } finally { setLoading(false) } }
  useEffect(() => { void load(); let source: EventSource | null = null; void subscribeToEvents(() => { void load() }).then((s) => { source = s }).catch(() => undefined); return () => source?.close() }, [])
  const redeem = async (id: string) => { try { const { data } = await benefitsAPI.redeem(id); alert(`Ваш промокод: ${data.promo_code}`); await load() } catch (e: any) { alert(e.response?.data?.error?.message || 'Не удалось получить промокод') } }
  const concierge = async () => { if (query.trim().length < 2) return; const { data } = await aiAPI.concierge(query); setRecommendations(data.benefits) }
  if (loading) return <main className="page"><p>Загрузка…</p></main>
  return <main className="page"><header className="topbar"><div><p className="eyebrow">Наггетсы30 · {user?.plan}</p><h1>Льготы для команды</h1><p>{user?.first_name} {user?.last_name}</p></div><button className="button secondary" onClick={logout}>Выйти</button></header>
    {error && <div className="notice error">{error}</div>}
    <section className="panel concierge"><div><p className="eyebrow">AI-консьерж</p><h2>Что вам сейчас нужно?</h2></div><div className="inline-form"><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Например: спорт рядом с офисом" /><button className="button" onClick={() => void concierge()}>Подобрать</button></div>{recommendations.length > 0 && <div className="chips">{recommendations.map((b) => <span className="chip" key={b.id}>{b.title}</span>)}</div>}</section>
    <section><div className="section-heading"><div><p className="eyebrow">Каталог</p><h2>Доступные предложения</h2></div><span className="muted">{benefits.length} предложений</span></div><div className="cards">{benefits.map((b) => <article className="card" key={b.id}><div className="card-head"><span className="tag">{b.category}</span>{b.your_discount_percent !== undefined && <strong className="discount">−{b.your_discount_percent}%</strong>}</div><h3>{b.title}</h3><p>{b.description}</p><div className="card-foot"><span className="muted">{b.merchant_name}</span><button className="button" disabled={b.already_redeemed} onClick={() => void redeem(b.id)}>{b.already_redeemed ? 'Уже получено' : 'Получить промокод'}</button></div></article>)}</div></section>
    <section className="two-columns"><div className="panel"><div className="section-heading"><h2>Мои промокоды</h2><span className="muted">{promos.length}</span></div>{promos.length === 0 ? <p className="muted">Промокодов пока нет.</p> : promos.map((p) => <div className="list-row" key={p.id}><div><strong>{p.code}</strong><p className="muted">{p.benefit_title} · до {new Date(p.expires_at).toLocaleDateString()}</p></div><span className={`status ${p.status.toLowerCase()}`}>{p.status}</span></div>)}</div><div className="panel"><h2>История</h2>{redemptions.length === 0 ? <p className="muted">Использований пока нет.</p> : redemptions.map((r) => <div className="list-row" key={r.id}><div><strong>{r.benefit_title}</strong><p className="muted">{r.merchant_name} · {new Date(r.created_at).toLocaleDateString()}</p></div><span className="status">{r.status}</span></div>)}</div></section>
  </main>
}
