import { useEffect, useState } from 'react'
import { adminAPI, type Benefit, type User } from '../api/client'
import { useAuth } from '../context/AuthContext'

type Tab = 'users' | 'benefits' | 'redemptions' | 'audit'
export default function PlatformAdminDashboard() {
  const { user, logout } = useAuth(); const [tab, setTab] = useState<Tab>('users'); const [users, setUsers] = useState<User[]>([]); const [benefits, setBenefits] = useState<Benefit[]>([]); const [redemptions, setRedemptions] = useState<any[]>([]); const [audit, setAudit] = useState<any[]>([]); const [loading, setLoading] = useState(true)
  const load = async () => { setLoading(true); try { const [u, b, r, a] = await Promise.all([adminAPI.users({ page: 1, page_size: 100 }), adminAPI.benefits({ page: 1, page_size: 100 }), adminAPI.redemptions({ page: 1, page_size: 50 }), adminAPI.auditLogs({ page: 1, page_size: 50 })]); setUsers(u.data.items); setBenefits(b.data.items); setRedemptions(r.data.items); setAudit(a.data.items) } finally { setLoading(false) } }
  useEffect(() => { void load() }, [])
  if (loading) return <main className="page"><p>Загрузка…</p></main>
  const tabs: [Tab, string, number][] = [['users', 'Пользователи', users.length], ['benefits', 'Льготы', benefits.length], ['redemptions', 'Погашения', redemptions.length], ['audit', 'Аудит', audit.length]]
  return <main className="page"><header className="topbar"><div><p className="eyebrow">Платформенное управление</p><h1>Операционный центр</h1><p>{user?.email}</p></div><button className="button secondary" onClick={logout}>Выйти</button></header><nav className="tabs">{tabs.map(([id, label, count]) => <button className={`tab ${tab === id ? 'active' : ''}`} onClick={() => setTab(id)} key={id}>{label} ({count})</button>)}</nav>{tab === 'users' && <section>{users.map((u) => <div className="list-row" key={u.id}><div><strong>{u.first_name} {u.last_name}</strong><p className="muted">{u.email} · {u.role} · {u.plan ?? '—'}</p></div><div className="row-actions"><span className={`status ${u.is_active ? 'issued' : 'expired'}`}>{u.is_active ? 'ACTIVE' : 'BLOCKED'}</span><button className="button secondary small" onClick={() => void adminAPI.setUserActive(u.id, !u.is_active).then(load)}>{u.is_active ? 'Заблокировать' : 'Разблокировать'}</button></div></div>)}</section>}{tab === 'benefits' && <section className="cards">{benefits.map((b) => <article className="card" key={b.id}><span className="tag">{b.category}</span><h3>{b.title}</h3><p>{b.description}</p><p className="muted">Merchant: {b.merchant_id}</p><div className="chips">{b.plan_offers?.map((o) => <span className="chip" key={o.plan}>{o.plan}: {o.discount_percent}%</span>)}</div></article>)}</section>}{tab === 'redemptions' && <section>{redemptions.map((r) => <div className="list-row" key={r.id}><div><strong>{r.benefit_id}</strong><p className="muted">Company: {r.company_id} · Employee: {r.employee_id}</p></div><span className="status">{r.status}</span></div>)}</section>}{tab === 'audit' && <section>{audit.map((entry) => <div className="list-row" key={entry.id}><div><strong>{entry.action}</strong><p className="muted">{entry.entity_type} · {entry.created_at}</p></div><code>{entry.entity_id ?? '—'}</code></div>)}</section>}</main>
}
